# Configuration File
site_name: "Docs : DNYFZR"

nav:
    - Home: index.md
    - Projects: projects.md
    - Developer Resources: 
      - Website: https://dnyfzr.github.io/resources/
      - Repo: https://github.com/DNYFZR/resources/
      
    - Social Links App:
      - Website: https://dnyfzr.github.io/SNWLNK/
      - Repo: https://github.com/DNYFZR/SNWLNK/
      - Live App: https://socials.streamlit.app/

    - Tennis App:
      - Website: https://dnyfzr.github.io/TennisApp/
      - Repo: https://github.com/DNYFZR/TennisApp/
      - Live App: https://tennis.streamlit.app/

    - Database API: 
      - Website: https://dnyfzr.github.io/DatabaseAPI/
      - Repo: https://github.com/DNYFZR/DatabaseAPI/
    
    - Spark Reactor: 
      - Website: https://dnyfzr.github.io/reactor/
      - Repo: https://github.com/DNYFZR/reactor/

theme:
  name: material
  
  features:
    - header.autohide
  
  palette:

    # Dark Mode  
    - scheme: slate
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
     
    # Light mode
    - scheme: default
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb 
          name: Switch to dark mode