# Configuration File
site_name: "ProjectHub"

nav:
    - Home: index.md
    - ATP Tour Stats App: tennisApp.md
    - Developer Resources: resources.md        
    - Link Sharing App: snwlnk.md
    - Postgres Database API: dbAPI.md
    - Spark Codebase Manager: reactor.md

theme:
  name: material

  font:
    text: DM Sans

  features:
    - header.autohide
  
  palette:
    # Dark Mode  
    - scheme: slate
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
     
    # Light mode
    - scheme: default
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb 
          name: Switch to dark mode
