# Configuration File
site_name: "ProjectHub"

nav:
    - Home: index.md
    - ResourceHub: https://dnyfzr.github.io/ResourceHub/
    - DevOpsHub: https://dnyfzr.github.io/DevOps/
    - ATP Tour Stats App: https://dnyfzr.github.io/TennisApp/
    - Link Sharing App: https://dnyfzr.github.io/SNWLNK/
    - Postgres Database API: https://dnyfzr.github.io/DatabaseAPI/
    - Spark Codebase Manager: https://dnyfzr.github.io/reactor/

theme:
  name: material

  font:
    text: DM Sans

  features:
    - header.autohide
  
  palette:
    # Dark Mode  
    - scheme: slate
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
     
    # Light mode
    - scheme: default
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb 
          name: Switch to dark mode
