# Configuration File
site_name: "ProjectHub"

nav:
    - Home: index.md

    - Link Sharing App: 
      - Home: snwlnk.md
      - App: https://socials.streamlit.app/

    - ATP Tour Stats App:
      - Home: tennisApp.md
      - App: https://tennis.streamlit.app/

    - Developer Resources: resources.md        
    - Postgres Database API: dbAPI.md
    - Spark Codebase Manager: reactor.md

theme:
  name: material
  
  font:
    text: DM Sans

  features:
    - header.autohide
  
  palette:

    # Dark Mode  
    - scheme: slate
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode
     
    # Light mode
    - scheme: default
      primary: blue
      accent: pink
      toggle:
          icon: material/lightbulb 
          name: Switch to dark mode