# Configuration File
site_name: DNYFZR

theme:
  name: material
  
  features:
    - header.autohide

  plugins:
  - blog:
      blog_dir: Articles/

  palette:

    # Dark Mode  
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
          icon: material/lightbulb-outline
          name: Switch to light mode

    # Light mode
    - scheme: default
      primary: teal
      accent: orange
      toggle:
          icon: material/lightbulb 
          name: Switch to dark mode